apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: APP_NAME
  namespace: APP_NAME
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - name: APP_NAME
          image: APP_IMAGE
          ports:
            - containerPort: APP_PORT
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
